### PR TITLE
Eliminate unneeded constructors

### PR DESCRIPTION
**Pull request by mernst**
The `Cumulate()` constructor private and is never used.
The two in `Bags.java` are not used, and they leave necessary fields unset, so they seem dangerous.

### CODE REVIEW

**Comment by sylvainhalle** [comment]
These constructors are present for deserialization purposes. Most deserialization libraries (including for example [Azrael](https://github.com/sylvainhalle/Azrael)) require each class to have a no-args constructor, so that they can call it through reflection in order to get an empty instance of an object --which is then filled directly by the library. These constructors are made private, and are not even used by the class itself, if they are not meant to be used outside of this particular purpose.

For this reason, I would tend to keep these constructors in the code of these classes.

**Comment by mernst** [comment]
Thank you for the explanation.  That makes sense.

It might be helpful to add a short comment stating the purpose of the constructors, such as "this constructor is used for deserialization".  I can make a pull request if you agree that this would be worthwhile.

**Comment by sylvainhalle** [comment]
Yes please, if you are willing to do this you are very welcome.

**Comment by mernst** [comment]
I created a new pull request: #64

**Pull request closed without merging**
